config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users
  get '/users', :to => 'users#index', as: 'users'
  get '/users/:id', :to => 'users#show', as: 'user'  
  resources :standups do
    resources :comments
  end
  root :to => "standups#index"
 

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :standup
  belongs_to :user
  validates :user, :presence => true
  validates :standup, :presence => true
  validates_presence_of :body
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user
  has_many :tasks
  accepts_nested_attributes_for :tasks, :reject_if => :all_blank, :allow_destroy => true
  validates_presence_of :title
  
  validate :user_quota, :on => :create 

  private 
  def user_quota
    if user.links.today.count >= 1
      errors.add(:base, "Exceeds daily limit")
    end
  end
end

app/models/standup.rb
class Standup < ActiveRecord::Base
  belongs_to :user
  validates :user, :presence => true
  has_many :tasks, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  accepts_nested_attributes_for :tasks, :reject_if => :all_blank, :allow_destroy => true
  validates_presence_of :title
  validate :user_quota, :on => :create 

  scope :newest_first, -> { order('created_at DESC') }

  def find_previous
    user.standups.where("(id < ?)", id).last
  end

  private 

  def user_quota
    if user.standups.today.count >= 1
      errors.add(:base, "Exceeds daily limit")
    end
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :standup, :dependent => :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 
  mount_uploader :image, ImageUploader

  has_many :comments

  has_many :standups  do
    def today
        where(:created_at => (Time.now.beginning_of_day..Time.now))
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :username, :image, :password, :email) }
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!

  def new
    @comment = Comment.new
  end

  def create
    @standup = Standup.find(params[:standup_id])
    @comment = @standup.comments.build(comment_params)
    
    @comment.user = current_user
    if @comment.save
      redirect_to @standup 
    else
      render "new"
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end

end

app/controllers/standups_controller.rb
class StandupsController < ApplicationController
  before_action :set_standup, :only => [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:index, :show]
  before_action :authorized_user, :only => [:edit, :update, :destroy]

  respond_to :html

  def index
    @standups = Standup.newest_first.paginate(:per_page => 5, :page => params[:page])
    respond_with(@standups)
  end

  def show
    @prev = @standup.find_previous 
    respond_with(@standup, @prev)
  end

  def new
    @standup = current_user.standups.build
    respond_with(@standup)
  end

  def edit
  end

  def create
    @standup = current_user.standups.build(standup_params)
    @standup.save
    respond_with(@standup)
  end

  def update
    @standup.update(standup_params)
    respond_with(@standup)
  end

  def destroy
    @standup.destroy
    respond_with(@standup)
  end

  private
  def set_standup
    @standup = Standup.find(params[:id])
  end

  def standup_params
    params.require(:standup).permit(:title, :content, tasks_attributes: [:id, :content, :done, :_destroy])
  end

  def authorized_user
    @standup = current_user.standups.find_by(id: params[:id])
    redirect_to standups_path, notice: "Not authorized to edit this standup" if @standup.nil?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :username, :email, :image, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/standups_helper.rb
module StandupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div>
	<%= comment.body %>
</div>

app/views/comments/_error.html.erb
<% if @comment.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
    <ul>
    <% @comment.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/comments/new.html.erb
<%= render "error" %>
<%= form_for ([:standup, @comment]) do |f| %>
  <%= f.label :body %><br>
  <%= f.text_area :body %><br>
  <br>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StandupApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="navbar navbar-default" role="navigation"><header class="navbar navbar-default" role="navigation">
  <div class="navbar-inner">
    <div class="container">
      <div id="logo" class="navbar-brand"><%= link_to "STANDUP/-app", root_path %></div>
        <p class="navbar-text pull-right">
          <% if user_signed_in? %>
            <ul class="nav navbar-nav navbar-right">
              Logged in as <strong><%= current_user.email %></strong>
              </br>
              <li><%= link_to "Submit standup", new_standup_path %></li>
              <li><%= link_to "View users", users_path, :class => "navbar-link" %></li>
              <li><%= link_to "Edit profile", edit_user_registration_path, :class => "navbar-link" %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => "navbar-link"  %></li>
          </ul>
        <% else %>
          <% if request.path != new_user_registration_path %>
            <ul class="nav navbar-nav pull-right">
              <li><%= link_to "Sign up", new_user_registration_path, :class => "navbar-link"  %></li>   
              <li><%= link_to "Login", new_user_session_path, :class => "navbar-link"  %></li>
            </ul> 
          <% end %> 
        <% end %>
      </p>  
    </div>
  </div>
</header>
    <div id="main_content" class="container">
      <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %> 

      <div id="content" class="col-md-9 center-block">
        <%= yield %>
      </div>
    </div>


</body>
</html>

app/views/standups/_error.html.erb
<% if standup.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(standup.errors.count, "error") %> prohibited this standup from being saved:</h2>
    <ul>
    <% standup.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/standups/_form.html.erb
<%= form_for @standup, html: { multipart: true} do |f| %>
 
 <%= render :partial => 'error', locals: { standup: @standup } %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  
  <%= f.fields_for :tasks do |task| %>
    <%= render 'task_fields', f: task %>
  <% end %>

  <div class="links">
    <%= link_to_add_association 'add task', f, :tasks, class: "btn btn-default add-button" %>
  </div>

  <div class="form-group">
    <div class="pull-right">
    <%= f.submit "Submit", class: "btn btn-lg btn-primary" %>
  </div>
  
<% end %>

app/views/standups/_task_fields.html.erb
<div class="form-inline.clearfix">  
  <div class="nested-fields">
    <div class="form-group">
      <%= f.label :content %>
      </br>
      <%= f.text_field :content, id:"Content", class: "form-input form-control", :autofocus => true  %>
      <%= link_to_remove_association "remove task", f, class: "form-button btn btn-default" %>
    </div>
    <div class="form-group">
      <%= f.check_box :done %>
      <%= f.label :done %>
  
    </div>
  </div>
</div>  

app/views/standups/edit.html.erb
<h1>Editing standup</h1>

<%= render "form" %>

<%= link_to "Show", @standup %> |
<%= link_to "Back", standups_path %>

app/views/standups/index.html.erb
<% @standups.each do |standup| %>
  <div class="link row clearfix">
    <h2>
      <%= link_to standup.title, standup %><br>
      <small class="author">Submitted <%= time_ago_in_words(standup.created_at) %> by <%= standup.user.name %></small>
    </h2>
  </div>
<% end %>

<%= will_paginate @standups, :class => "digg_pagination" %>

app/views/standups/new.html.erb
<h1>New Standup</h1>

<%= render 'form' %>

<%= link_to 'Back', standups_path %>

app/views/standups/show.html.erb
<div class="page-header">
	<div class="comments_title">
		<h1><a href="#"><%= @standup.title %></a><br> <small>Submitted by <%= @standup.user.name %></small></h1>
	</div>	
</div>
<h2>Current tasks:</h2>
<% @standup.tasks.each do |task| %>
	<div id="comment">
		<li class="list-group-item"><%= task.content %></li>
	</div>	
<% end %>	
</hr>
<div class="link row clearfix">
<h2>Previous tasks:</h2>
	<% if @prev != nil%>
		<% @prev.tasks.each do |task| %>
			<div id="comment">
				<li class="list-group-item"><%= task.content %></li>
			</div>
		<% end %>
	<% else %>
		<h3>No previous tasks</h3>
	<% end %>
	
	<h2><%= @standup.comments.count %> Comments</h2>

	<% @standup.comments.each do |comment| %>

		<strong>Posted by: <strong><%= comment.user.username %><br><%= comment.body %>
	<% end %>
	
	<% if @standup.user == current_user -%>
	<div class="btn-group">
		| <%= link_to "Add comment", new_standup_comment_path(@standup) %> 
		| <%= link_to 'Edit', edit_standup_path(@standup), class: "btn btn-default" %>
		| <%= link_to 'Destroy', @standup, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "btn btn-default"%>
	</div>
<% end %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user, :html => {:multipart => true}) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= image_tag @user.image_url(:thumb) if @user.image? %>
  </div>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form'%>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table class="table">
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>

      <tr>
        <% if user.image? %>
          <td><%= image_tag user.image_url(:thumb).to_s, :class => 'img-thumbnail' %></td>
        <% else %>
           <td><%= image_tag 'default.png', size: "100x100", :class => 'img-thumbnail' %></td>
        <% end %>  
        <td><%= user.name %></td>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
   <h2><%= @user.name %> </h2><%= @user.username %>
</p>


  


<p>
  <% if @user.image? %>
  	<td><%= image_tag @user.image_url(:thumb).to_s, :class => 'img-thumbnail' %></td>
  <% else %>
  	<td><%= image_tag 'default.png', size: "100x100", :class => 'img-thumbnail' %></td>
  <% end %>  
</p>

<%= link_to 'Back', users_path %>